// Generated by CoffeeScript 1.8.0
(function() {
  var loadImages;

  loadImages = function() {
    return function(path, resolve, reject, notify) {
      var img;
      img = new Image;
      img.onload = function() {
        return resolve(img);
      };
      img.onerror = function(e) {
        return reject(e);
      };
      return img.src = path;
    };
  };

  module.exports = loadImages;

}).call(this);
