// Generated by CoffeeScript 1.8.0
(function() {
  var loadImages;

  loadImages = function() {
    return function(path, resolve, reject, notify) {
      var img;
      img = new Image;
      img.onload = function() {
        resolve(img);
      };
      img.onerror = function(evt) {
        var err;
        err = new Error('Image failed to load. See the attached "event" and "image" attributes for details.');
        err.event = evt;
        err.image = img;
        reject(err);
      };
      return img.src = path;
    };
  };

  module.exports = loadImages;

}).call(this);
